version : '3.8'
services:
#  ruoyi-nacos:
#    container_name: ruoyi-nacos
#    build:
#      context: ./nacos
#      args:
#        NACOS_VERSION: ${NACOS_VERSION}
#    environment:
#      MODE: "${NACOS_MODE}"
#      MYSQL_DATABASE_NUM: "${NACOS_MYSQL_DATABASE_NUM}"
#      MYSQL_SERVICE_HOST: "${MYSQL_CONTAINER_NAME}"
#      MYSQL_SERVICE_DB_NAME: "${NACOS_MYSQL_SERVICE_DB_NAME}"
#      MYSQL_SERVICE_DB_PARAM: "${NACOS_MYSQL_SERVICE_DB_PARAM}"
#      MYSQL_SERVICE_USER: "${NACOS_MYSQL_SERVICE_USER}"
#      MYSQL_SERVICE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      TZ: "$TZ"
#    volumes:
#      - ./nacos/logs/:/home/nacos/logs
#      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
#    ports:
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
#    depends_on:
#      - ruoyi-mysql


  ruoyi-nacos1:
    container_name: ruoyi-nacos1
    build:
      context: ./nacos
      args:
        NACOS_VERSION: ${NACOS_VERSION}
    environment:
      MODE: "${NACOS_MODE}"
      NACOS_SERVERS: "${NACOS_SERVERS}"
      MYSQL_DATABASE_NUM: "${NACOS_MYSQL_DATABASE_NUM}"
      MYSQL_SERVICE_HOST: "${MYSQL_CONTAINER_NAME}"
      MYSQL_SERVICE_DB_NAME: "${NACOS_MYSQL_SERVICE_DB_NAME}"
      MYSQL_SERVICE_DB_PARAM: "${NACOS_MYSQL_SERVICE_DB_PARAM}"
      MYSQL_SERVICE_USER: "${NACOS_MYSQL_SERVICE_USER}"
      MYSQL_SERVICE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "11848:8848"
      - "11148:9848"
      - "11849:9849"
    depends_on:
      - ruoyi-mysql
  ruoyi-nacos2:
    container_name: ruoyi-nacos2
    build:
      context: ./nacos
      args:
        NACOS_VERSION: ${NACOS_VERSION}
    environment:
      MODE: "${NACOS_MODE}"
      NACOS_SERVERS: "${NACOS_SERVERS}"
      MYSQL_DATABASE_NUM: "${NACOS_MYSQL_DATABASE_NUM}"
      MYSQL_SERVICE_HOST: "${MYSQL_CONTAINER_NAME}"
      MYSQL_SERVICE_DB_NAME: "${NACOS_MYSQL_SERVICE_DB_NAME}"
      MYSQL_SERVICE_DB_PARAM: "${NACOS_MYSQL_SERVICE_DB_PARAM}"
      MYSQL_SERVICE_USER: "${NACOS_MYSQL_SERVICE_USER}"
      MYSQL_SERVICE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "12848:8848"
      - "12248:9848"
      - "12849:9849"
    depends_on:
      - ruoyi-mysql
  ruoyi-nacos3:
    container_name: ruoyi-nacos3
    build:
      context: ./nacos
      args:
        NACOS_VERSION: ${NACOS_VERSION}
    environment:
      MODE: "${NACOS_MODE}"
      NACOS_SERVERS: "${NACOS_SERVERS}"
      MYSQL_DATABASE_NUM: "${NACOS_MYSQL_DATABASE_NUM}"
      MYSQL_SERVICE_HOST: "${MYSQL_CONTAINER_NAME}"
      MYSQL_SERVICE_DB_NAME: "${NACOS_MYSQL_SERVICE_DB_NAME}"
      MYSQL_SERVICE_DB_PARAM: "${NACOS_MYSQL_SERVICE_DB_PARAM}"
      MYSQL_SERVICE_USER: "${NACOS_MYSQL_SERVICE_USER}"
      MYSQL_SERVICE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "13848:8848"
      - "13348:9848"
      - "13849:9849"
    depends_on:
      - ruoyi-mysql

  ruoyi-mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    platform: linux/amd64
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: "$TZ"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  ruoyi-redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    environment:
      TZ: "$TZ"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/ruoyi/redis/redis.conf
      - ./redis/data:/data
  ruoyi-nginx:
    container_name: ruoyi-nginx
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    environment:
      TZ: "$TZ"
    ports:
      - "80:80"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./nginx/html/dist:/home/ruoyi/projects/ruoyi-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/conf.d:/etc/nginx/conf.d

#  ruoyi-gateway:
#    container_name: ruoyi-gateway
#    build:
#      context: ./ruoyi/gateway
#      dockerfile: dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ruoyi-redis
#    links:
#      - ruoyi-redis
#  ruoyi-auth:
#    container_name: ruoyi-auth
#    build:
#      context: ./ruoyi/auth
#      dockerfile: dockerfile
#    ports:
#      - "9200:9200"
#    depends_on:
#      - ruoyi-redis
#    links:
#      - ruoyi-redis
#  ruoyi-modules-system:
#    container_name: ruoyi-modules-system
#    build:
#      context: ./ruoyi/modules/system
#      dockerfile: dockerfile
#    ports:
#      - "9201:9201"
#    depends_on:
#      - ruoyi-redis
#      - ruoyi-mysql
#    links:
#      - ruoyi-redis
#      - ruoyi-mysql
#  ruoyi-modules-gen:
#    container_name: ruoyi-modules-gen
#    build:
#      context: ./ruoyi/modules/gen
#      dockerfile: dockerfile
#    ports:
#      - "9202:9202"
#    depends_on:
#      - ruoyi-mysql
#    links:
#      - ruoyi-mysql
#  ruoyi-modules-job:
#    container_name: ruoyi-modules-job
#    build:
#      context: ./ruoyi/modules/job
#      dockerfile: dockerfile
#    ports:
#      - "9203:9203"
#    depends_on:
#      - ruoyi-mysql
#    links:
#      - ruoyi-mysql
#  ruoyi-modules-file:
#    container_name: ruoyi-modules-file
#    build:
#      context: ./ruoyi/modules/file
#      dockerfile: dockerfile
#    ports:
#      - "9300:9300"
#    volumes:
#    - ./ruoyi/uploadPath:/home/ruoyi/uploadPath
#  ruoyi-visual-monitor:
#    container_name: ruoyi-visual-monitor
#    build:
#      context: ./ruoyi/visual/monitor
#      dockerfile: dockerfile
#    ports:
#      - "9100:9100"
